# site properties and page defaults
# site properties and page defaults
url: "https://cnueifn-commits.github.io"
baseurl: "/cnue-ifn-site"
title: 청주교육대학교 기초수리력 연구소
subtitle: Cheongju National University of Education Institute for Foundational Numeracy
description: 학생이 기초 수준의 수리력을 갖출 수 있게 하는 교육 방안을 탐구하는 전문 연구 기관입니다.
header: images/background.jpg
footer: images/background.jpg
image: images/share.png
proofer: false
dark_mode: false

# site social media and other links
links:
  email: cnue.ifn@gmail.com

### jekyll settings

# front matter defaults
defaults:
  # all markdown files
  - scope:
      path: ""
    values:
      layout: default
  # markdown files in /_members
  - scope:
      type: "members"
    values:
      layout: member
  # markdown files in /_posts
  - scope:
      type: "posts"
    values:
      layout: post

collections:
  # generate page for each member
  members:
    output: true
  # generate page for each post
  posts:
    output: true

# jekyll plugins
plugins:
  - jekyll-spaceship
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-feed
  - jekyll-last-modified-at

# code block syntax highlighting
highlighter: rouge

# jekyll theme
theme: null

# sass settings
sass:
  sass_dir: _styles

# force jekyll to include certain files/folders
include:
  - _styles
  - _scripts

# force jekyll to exclude certain files/folders
exclude:
  - README.md
  - LICENSE.md
  - CITATION.cff

# configure jekyll spaceship
jekyll-spaceship:
  mathjax-processor:
    src:
      - https://cdn.jsdelivr.net/npm/mathjax@4/tex-mml-chtml.js
